### PR TITLE
Revert "Upgrade plugins, make Java 8 compatible"

### PR DESCRIPTION
**Pull request by mick-stewart73**
Reverts ikasanEIP/ikasan#173

### CODE REVIEW

**Comment by karianna** [comment]
Did the revert have to occur due to the failing tests I mentioned?

**Comment by mick-stewart73** [comment]
Hi Martin, I was in a bit of a rush so reverted but the merge broke the build. I will try to get onto it today and give you details of what broke.

Cheers
Mick

**Comment by karianna** [comment]
Thanks, I know that there were failing tests (the Travis build warned of
that), but that seemed to be due to a Java 7 v 8 subtlety.

Cheers,
Martijn

**Comment by andrzej-majewski** [comment]
Martijn,

I am not sure it that is of any help but have you instructed travis is to run with jdk8?

At the moment the build is forced to run on jdk7 

.travis.yml

sudo: false
language: java
jdk:
  - oraclejdk7

**Pull request merged**
