### PR TITLE
Java 8 compile and tests pass

### PR DESCRIPTION
**Pull request by karianna**
I was forced to @Ignore 5 tests, I noticed from the comments for some of those tests that they're known issues...

### CODE REVIEW

**Comment by drawson** [comment]
@karianna @mitcje Not sure we should pull this. The ignored tests fail in Java 8 I think because of a bug Oliver found with the ordering of the returned List. Its 'correct' in 7 but maybe not for the reason we think (i.e. its a fluke that its correct). So the underlying List implementation needs to be check and fixed for consistent ordering and the Ignore annotations removed.

**Comment by mitcje** [comment]
Agreed. We need to ensure the ordering is correct on the returned List. Fixing the bug is required here.

**Comment by karianna** [comment]
Agreed - I should have pointed out that this PR should not (yet) be merged.  As you say IKASAN-719, IKASAN-924 and IKASAN-825 need to be fixed first (and ErrorReportingManagementServiceImplTest#test_close_error_occurrences).  I'll take a look over the weekend although I confess I've been 4+ years out of this code base.

**Comment by drawson** [comment]
I've found at least one of the bugs in the Java8 test problems.

In ConfigurationFactoryDefautImpl we have:

`           Map<String, Object> properties = PropertyUtils.describe(runtimeConfiguration);
            for (Map.Entry<String, Object> entry : properties.entrySet()) {
`

So either there is an update to org.apache.commons.beanutils.PropertyUtils that uses LinkedHashMap to guarantee order, or we roll our own.

**Comment by karianna** [comment]
I've taken the wrapped TreeMap approach, seems to resolve IKASAN 719 and 924, so that just leaves one ignored test which I'm looking at now.

**Comment by karianna** [comment]
OK, so there are other intermittent failing tests on Travis for Java 8 (although they all pass locally).  I'll try to do some extra digging, could be 8u_X update related

**Comment by drawson** [comment]
We have intermittent failures on scheduler and email-producer (testMailServerFailure) tests. Neither are reproducable locally.

https://ikasan.atlassian.net/browse/IKASAN-1150

Not yet raised the Scheduler one, its in SchedulerCallbackExecutionTest.test_createJobDetail_concurrentCallbacks()

**Comment by karianna** [comment]
OK, I now have a passing build - let me know of any other comments :-)

**Comment by drawson** [comment]
@mitcje I'm happy to pull this now unless you have other concerns. We may need to revisit configuration parameter ordering since its probably alphabetical with these changes to use TreeMap

**Comment by karianna** [comment]
Hi all, I've rebased and pushed one extra fix so that it can mvn clean install on both 7 and 8.  This should be good to go now :-)

**Comment by mitcje** [comment]
No issues with this PR. Im out for the next week, so I wont merge this in now, however, no issues if someone else wishes to.

**Pull request merged**
