### PR TITLE
IKASAN-1298 - IkasanApplication.getIkasanApplication does not allow f…

### PR DESCRIPTION
**Pull request by kieronedwards**
Please look at the coment on https://ikasan.atlassian.net/browse/IKASAN-1298.

### CODE REVIEW

**Comment by mitcje** [comment]
There seems to be a method for getting Application Context which I dont understand. Also where is the change to the IkasanApplicationFactory for the alternate creation passing context ??

**Comment by kieronedwards** [comment]
Agree that context() method should be private, its just a method to give a nicer error if someone accidentally uses the spring default constructor.  Fixing now ...

I didnt change the IkasanApplicationFactory as I didnt create the IkasanApplicationSpring class - this has no meaning outside of a spring boot context (the close method on it is spring boot specific). I created the DefaultSpringBootIkasanApplication class instead 

The option of using the IkasanApplicationFactory to create a spring boot application with external spring boot config can be investigated, to do this cleanly you would need an sb application property or a marker interface that is scanned for.

**Comment by mitcje** [comment]
Sorry - merged this as you were commenting. I dont see how this will work in its current form. Lets catch up on this tomorrow.

**Comment by andrzej-majewski** [comment]
I thought this was not complete yet. Can we revert? I dont think we should be merging half baked changes.

**Pull request merged**
