### PR TITLE
IKASAN-1580 - allow invokers to correctly call proxied classes with F…

### PR DESCRIPTION
**Pull request by drawson**
…lowEvent

### CODE REVIEW

**Comment by mitcje** [comment]
I am not convinced this is the correct fix at present as I am still unclear on the actual cause of this. I need to look at the code and get something repeatable where this issue is demonstrated. Not saying this isnt the fix, but I still dont undersatnd why/where the root cause is.

**Comment by drawson** [comment]
@mitcje The failure can be seen in the unit tests for both Converter and Broker invokers, i.e. run the new test with the old code.

The failure is more obvious for a Broker since that could be pointcut. It fails on a Coverter due to some strange pointcut match with the older version of the mapping dao pointcut expression.

**Comment by andrzej-majewski** [comment]
The code changes look good. Shouldn't the same change be applied across all components:
- splitters
- producers
- routers

Which then raises a question why would any of these components be pointcut? 

Only components which require pointcut is consumer, broker and producer might require pointcut. All three (consumer,producer,broker) are only components which should be cutting a boundary of a call to external system or XA resource.

**Comment by mitcje** [comment]
Still not clear on why developers implementing with Ikasan would need to pointcut any Ikasan code. If they have transactional behaviour through a consumer, broker, producer, or whatever compoonent, then that should be pointcut on the code the developer is introducing shouldnt it?

**Comment by drawson** [comment]
Not required, not a bug if developers use correct provided pointcuts

**Pull request closed without merging**
