### PR TITLE
IKASAN-1348, IKASAN-1345 upgrade to solr 7.1.0. Add funcationality re…

### PR DESCRIPTION
**Pull request by mick-stewart73**
…quired by solr security.

### CODE REVIEW

**Comment by andrzej-majewski** [comment]
I just saw log4j file along all files added. Can you please remove it and get rid of any log4j pom dependencies if we have any use slf4j

**Comment by andrzej-majewski** [comment]
Also what are all these files do we rally need them?


R ikasaneip/solr/solr-client/src/test/resources/solr/configsets/minimal-dismax/conf/schema.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/configsets/minimal-dismax/conf/solrconfig.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/configsets/minimal/conf/schema.xml (0)
A ikasaneip/solr/solr-client/src/test/resources/solr/configsets/minimal/conf/solrconfig.xml (47)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/addfields.updateprocessor.js (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/analyzingInfixSuggest.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-currency.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-error-solrconfig.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-mp-solrconfig.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-mpf-solrconfig.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-analyzer-class-and-nested.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-bogus-analysis-parameters.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-bogus-field-parameters.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-codec-global-vs-ft-mismatch.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-currency-dynamic-multivalued.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-currency-ft-bogus-code-in-xml.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-currency-ft-bogus-default-code.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-currency-ft-multivalued.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-currency-ft-oer-norates.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-currency-multivalued.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-default-operator.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-defaultsearchfield.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-dup-dynamicField.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-dup-field.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-dup-fieldType.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-dynamicfield-default-val.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-dynamicfield-required.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-external-filefield.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-init-error.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-misplaced-asterisk-copyfield-dest-should-fail-test.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-misplaced-asterisk-copyfield-source-should-fail-test.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-multiple-asterisk-copyfield-dest-should-fail-test.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-multiple-asterisk-copyfield-source-should-fail-test.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-non-glob-copyfield-source-matching-nothing-should-fail-test.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-nontext-analyzer.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-not-indexed-but-norms.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-not-indexed-but-pos.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-not-indexed-but-tf.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-omit-tf-but-not-pos.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-sim-default-does-not-exist.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-sim-default-has-no-explicit-sim.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-sim-global-vs-ft-mismatch.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-sweetspot-both-tf.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-sweetspot-partial-baseline.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-sweetspot-partial-hyperbolic.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-sweetspot-partial-norms.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-uniquekey-is-copyfield-dest.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-uniquekey-multivalued.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-uniquekey-uses-default.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-schema-unsupported-docValues.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-solrconfig-bogus-scriptengine-name.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-solrconfig-invalid-scriptfile.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-solrconfig-managed-schema-named-schema.xml.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-solrconfig-missing-scriptfile.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-solrconfig-multiple-cfs.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-solrconfig-multiple-dirfactory.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-solrconfig-multiple-indexconfigs.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-solrconfig-nrtmode.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-solrconfig-schema-mutable-but-not-managed.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad-solrconfig-unexpected-schema-attribute.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/bad_solrconfig.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/blendedInfixSuggest.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/compoundDictionary.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/conditional.updateprocessor.js (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/cross-compatible.js (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/currency.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/da_UTF8.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/da_compoundDictionary.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/elevate.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/enumsConfig.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/freeTextSuggest.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/frenchArticles.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/fuzzysuggest.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/hunspell-test.aff (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/hunspell-test.dic (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/hyphenation.dtd (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/jasuggest.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/keep-1.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/keep-2.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/mapping-ISOLatin1Accent.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/missing.functions.updateprocessor.js (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/missleading.extension.updateprocessor.js.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/multiword-synonyms.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/old_synonyms.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/open-exchange-rates.json (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/phrasesuggest.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/protwords.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/regex-boost-processor-test.txt (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-HighlighterMaxOffsetTest.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-SimpleTextCodec.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-add-schema-fields-update-processor.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-behavior.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-binaryfield.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-blockjoinfacetcomponent.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-bm25.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-charfilters.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-class-name-shortening-on-serialization.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-classification.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-collate-dv.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-collate.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-copyfield-test.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-custom-field.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-customfield.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-dfi.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-dfr.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-distrib-interval-faceting.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-distributed-missing-sort.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-docValues.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-docValuesFaceting.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-docValuesJoin.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-docValuesMissing.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-docValuesMulti.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-eff.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-enums.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-field-sort-values.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-folding.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-graph.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-hash.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-ib.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-id-and-version-fields-only.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-inplace-updates.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-lmdirichlet.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-lmjelinekmercer.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-luceneMatchVersion.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-minimal-atomic-stress.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-minimal-numeric-join.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-minimal-with-another-uniqkey.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-minimal.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-multiword-synonyms.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-non-stored-docvalues.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-not-required-unique-key.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-null-charfilters-analyzer.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-numeric.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-one-field-no-dynamic-field-unique-key.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-one-field-no-dynamic-field.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-phrasesuggest.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-point.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-postingshighlight.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-preanalyzed.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-psuedo-fields.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-replication1.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-replication2.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-required-fields.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-rest-lucene-match-version.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-rest.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-reversed.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-sim-default-override.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-sim.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-simpleqpplugin.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-single-dynamic-copy-field.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-snippet-field.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-snippet-type.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-snippet-types.incl (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-sortingresponse.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-sorts.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-spatial.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-spellchecker.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-sql.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-sweetspot.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-synonym-tokenizer.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-tfidf.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-tiny.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-trie.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-unifiedhighlight.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-version-dv.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-version-indexed.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema-xinclude.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema11.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema12.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema15.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema_codec.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schema_latest.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/schemasurround.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-SOLR-749.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-add-schema-fields-update-processor-chains.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-altdirectory.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-analytics-query.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-basic.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-blockjoinfacetcomponent.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-cache-enable-disable.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-caching.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-cdcr.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-cdcrupdatelog.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-classification.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-collapseqparser.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-components-name.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-configurerecoverystrategy.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-customrecoverystrategy.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-deeppaging.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-defaults.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-delaying-component.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-delpolicy1.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-delpolicy2.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-distrib-update-processor-chains.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-doc-expire-update-processor.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-doctransformers.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-elevate.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-externalversionconstraint.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-functionquery.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-hash.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-headers.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-highlight.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-implicitproperties.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-indexconfig-mergepolicyfactory.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-indexconfig.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-indexmetrics.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-infixsuggesters.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-infostream-logging.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-lazywriter.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-logmergepolicy.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-logmergepolicyfactory.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-managed-schema-test.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-managed-schema.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-master-throttled.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-master.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-master1-keepOneBackup.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-master1.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-master2.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-master3.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-mergepolicy-defaults.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-mergepolicy-legacy.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-mergepolicy-nocfs.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-mergepolicyfactory-nocfs.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-minimal-version6.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-minimal.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-nocache.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-nomergepolicyfactory.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-noopregen.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-paramset.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-parsing-update-processor-chains.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-phrasesuggest.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-plugcollector.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-postingshighlight.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-query-parser-init.xml (2)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-querysender-noquery.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-querysender.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-repeater.xml (0)
R ikasaneip/solr/solr-client/src/test/resources/solr/ikasan/conf/solrconfig-reqHandler.incl (0)

**Comment by mick-stewart73** [comment]
Files are required by embeded solr. They were already in GIT. However, the core name was changed, hence i believe that they are popping up as a result.

**Comment by mick-stewart73** [comment]
Will take a look at log4j. I did not explicitly do anything in relation to this...

**Pull request merged**
