### PR TITLE
Attempt to redo PR against 1.1.x

### PR DESCRIPTION
**Pull request by karianna**

### CODE REVIEW

**Comment by karianna** [comment]
Actual changes can be found at https://github.com/ikasanEIP/ikasan/pull/151/files/?w=1

**Comment by karianna** [comment]
Travis fails, but I think that's a config change you guys need to make there to authenticate against the Maven central and/or Ikasan Nexus.

**Comment by drawson** [comment]
@mitcje Can you take a look at this - for some reason it gives a 401 Unauthorized on oss.sonatype.org snapshot repo. Any ideas?

**Comment by mitcje** [comment]
@andrzej-majewski Any chance you can have a look at the travis to Sonotype issue above? I can provide credentials on Sonotype as required for initial testing of this. Let me know.

**Comment by andrzej-majewski** [comment]
I am not sure what went wrong, our travis script specifies OSS user and pass. However I am not sure how that works on PR. 

echo "<settings><servers><server><id>ikasaneip-snapshots</id><username>\${env.OSS_IKASAN_USER}</username><password>\${env.OSS_IKASAN_PASS}</password></server>


The pull request is no longer there so I cannot investigate. 
https://travis-ci.org/ikasanEIP/ikasan/builds/91811670

Travis build on branches are working fine:
https://travis-ci.org/ikasanEIP/ikasan/branches

**Pull request merged**
