### PR TITLE
2.0.x ikasan 1371

### PR DESCRIPTION
**Pull request by mick-stewart73**
Completed sybase hibernate dialect work.

### CODE REVIEW

**Comment by mick-stewart73** [comment]
Andrzej I could not get the logging working. I merged your branch here. What am I missing? Also please elaborate on why you think the dialect does not belong in Ikasan? In my opinion it is the place for it in the case that other sybase users could leverage this if they use Ikasan. The end goal is to contact the hibernate guys to see if they can change the behavior in their framework.

**Comment by andrzej-majewski** [comment]
Ikasan is not the place to fix shortcomings of Sybase DB and hibernate dialect. Ikasan framework is agnostic to DB used hence it is to the user to deal with the DB persistence shortcomings. We can provide advice in the documentation to suggest what to do to resolve the sybase issue.

**Comment by andrzej-majewski** [comment]
@mick-stewart73 
Can you please close this pull request and open a new one which does not contain the log4j changes?

We dont need to mix the two pull requests.  

Please remove the commit:
IKASAN-1366 - remove dependency on log4j move to slf4j
and Merge


The log4j touches itself over 140 files, this is blurring the picture of what the  IKASAN-1371 change is about.

**Comment by andrzej-majewski** [comment]
Moved to https://github.com/ikasanEIP/ikasan/pull/411

**Comment by mick-stewart73** [comment]
That is a pain Andrzej. You wanted me to test with Sybase so the merge was the pragmatic thing to do as I had a lot of testing against Sybase to do. Pity the fix did not work. Not that I don't agree with what you are saying, but we are pushed for time at the moment as I understood we are trying to cut a release before the end of 2017 when chatting with Jeff.

Regarding the dialect, see what Jeff says as I have discussed with him and he agreed to add to Ikasan.

**Comment by mick-stewart73** [comment]
Andrzej, I had a look and it is non-trivial to unpick the merge-commit. Sorry but I do not have much bandwidth over this weekend to do this so please proceed as is.

I am sorry When I merged you stuff I just assumed that the log4j references in pom and config only had been changed. I was not aware of code changes as i did not look. I had mentioned to Jun this was a mistake in hindsight a couple of days ago, but we are where we are.

I still do not understand why it is not working. Can you please share what the problem is?

If you insist that this can not be pulled, then I will try to unpick on Tuesday.

**Comment by andrzej-majewski** [comment]
I have already unpicked this for you. it is on the other branch. 
Please just use:
https://github.com/ikasanEIP/ikasan/tree/2.0.x-IKASAN-1371-v2

I have cherry picked only your commits.

I will test and verify what is going on with log4j and logging.

**Comment by mick-stewart73** [comment]
@andrzej-majewski thanks for cherry picking, I have retested on your new branch. There is no logging on the new branch as there had been changes to the dashboard jar pom which seems to have contributed to the absence of logging altogether, however the changes i have made are still OK. I will leave for you to sort out the logging and then pull in. I will close and delete this branch. FYI I find the comments on GIT difficult to follow as they do not maintain a chronology like JIRA, and I do not get notifications sent to me for these.

**Pull request closed without merging**
