### PR TITLE
IKASAN-1863 - For configured components, if they do not have an insta…

### PR DESCRIPTION
**Pull request by mitcje**
…nce of their configuration bean set, then try to create and set it.

### CODE REVIEW

**Review by kieronedwards — COMMENTED** [review]
@mitcje what is the use case for this - if a component is configured but has null configuration shouldnt we be throwing an exception, or is there a specific case where this is intended behaviour by the developer 

Can we add a WARN log message where this is done as is a deviation from normal behaviour ? Also an ERROR message if no configuration coud be instantiated.

Is the String parsing necessary can you use the usual reflection classes ? e.g. 

```java

    protected Object generateConfiguredInstance(Configured configured)
    {
        logger.warn("Component [{}] is configured but has no configuration instance set will attempt to instantiate",
            configured.toString());
        Type[] types = configured.getClass().getGenericInterfaces();
        for(Type type:types)
        {
                if (type instanceof ParameterizedType && Configured.class.isAssignableFrom(
                    (Class)((ParameterizedType) type).getRawType())) {
                    Type configurationType = ((ParameterizedType) type).getActualTypeArguments()[0];
                    try {
                        if (configurationType instanceof Class)
                        return ((Class)configurationType).getConstructor().newInstance();
                    } catch (InvocationTargetException | InstantiationException | IllegalAccessException
                        | NoSuchMethodException e) {
                    }

                }
        }
        logger.error("Unable to instantiate configuration for component [{}]", configured);
        return null;
    }

```

Many Thanks

**Comment by mitcje** [comment]
We throw an exception now, and its just annoying to find this at runtime. The idea here is to pre-populate and create as much as possible in the absence of the developer doing this.

**Review by kieronedwards — APPROVED** [review]

**Comment by mitcje** [comment]
I swapped out part of the configuration for the suggested code from @kieronedwards  as I think that is much cleaner. PR updated and requires subsequent approval.

**Review by kieronedwards — APPROVED** [review]
Changes look good. Approved.

**Pull request merged**
