### PR TITLE
2.0.3 ikasan 1466 - new implementation of MessageFilter

### PR DESCRIPTION
**Pull request by andrzej-majewski**
Due to shortcoming of existing implementation of Message filter we providing new implementation. DefultMessageFilterService is leveraging old and new Dao and is forcing users to migrate.

@mitcje @drawson can you please review?

### CODE REVIEW

**Comment by drawson** [comment]
@andrzej-majewski  @mitcje  I've commented on the files changed, I think some bits are incorrect, please can you double check?

**Comment by andrzej-majewski** [comment]
@drawson  I cannot see your comments.

**Comment by drawson** [comment]
@andrzej-majewski  Sorry, i forgot to submit the review for changes. Should be above now.

**Comment by mitcje** [comment]
Is this complete and ready for review ?

**Comment by andrzej-majewski** [comment]
Need to review and see changes again.

**Pull request closed without merging**
